### ISSUE TITLE
Lecture(s) and Labs need to be pushed for next week.

### ISSUE THREAD

**Issue by DrPumpkin** [StewartTaylor/CST-238#2]
Next week we're covering Embedding C++.

Monday: Embedding C++, Layouts (Row, Column, Grid)
Wednesday: Embedding C++, Input (Keyboard + Text)
Thursday: Signals/Slots, previous topics of M + W.
Friday: Puzzle that encompasses M + W's lecture.

**Comment by Tpimp** [comment]
Stu just to be clear the two lectures I intended to be on Qml. The embedded C++ was going to be the lab discussion. With the C++ being solitary. Then have Qml make a call to a C++ class. But I'll see what you guys come up with and help where I can.
